project:
  type: website
  output-dir: ../docs

website:
  title: "Samantha Howitt"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Publications.qmd
        text: Research

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: source

